import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.78'
    id 'net.darkhax.curseforgegradle' version '1.1.28'
    id 'com.modrinth.minotaur' version '2.10.0'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()

            programArguments.addAll '--username', 'Quarris'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        clientTester {
            client()

            programArguments.addAll '--username', 'Tester'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name "Curse Maven"
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }

    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }

    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    implementation "curse.maven:jade-324717:${jade_version}"

    implementation "curse.maven:pretty-pipes-376737:$pp_version"
    implementation "curse.maven:pretty-pipes-fluids-479142:$ppf_version"
    implementation "curse.maven:large-fluid-tank-291006:$tank_version"
    implementation "curse.maven:scalable-cats-force-320926:$scala_version"

    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    compileOnly("dev.emi:emi-neoforge:${emi_version}+${minecraft_version}:api")

    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")
    runtimeOnly("dev.emi:emi-neoforge:${emi_version}+${minecraft_version}")
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

var changelogText = file('changelog.md').exists() ? file('changelog.md').text : ""

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    group = 'publishing'
    description = 'Upload project to CurseForge'
    dependsOn tasks.jar

    apiToken = System.getenv('CURSEFORGE_API_PUBLISH')
    disableVersionDetection()

    def mainFile = upload(curseforge_id, tasks.jar)
    mainFile.displayName = "$mod_name v$project.version ($minecraft_version)"
    mainFile.releaseType = release_type
    mainFile.changelog = changelogText
    mainFile.changelogType = 'markdown'
    mainFile.addModLoader('NeoForge')
    mainFile.addGameVersion(minecraft_version)
    mainFile.addJavaVersion('Java 21')
    mainFile.addEnvironment('Client', 'Server')
}

modrinth {
    token = System.getenv('MODRINTH_API_PUBLISH')
    projectId = modrinth_id
    versionNumber = project.version
    versionName = "$mod_name v$project.version ($minecraft_version)"
    versionType = release_type
    uploadFile = jar
    gameVersions = [minecraft_version] // Add the Minecraft versions you're targeting
    loaders = ["neoforge"]
    changelog = changelogText
}

